version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Frontend
      - "3333:3333"  # Backend API
      - "3000:3000"  # Tokenizer service
    environment:
      DATABASE_URL: postgresql://postgres:xdkfjZgTJJDjLFXDxqqyiryNZyUyMuaO@trolley.proxy.rlwy.net:13061/railway
      JWT_SECRET: your-jwt-secret-change-this
      APP_URL: http://lunary.188.245.152.205.sslip.io
      API_URL: http://lunary.188.245.152.205.sslip.io:3333
      NEXT_PUBLIC_API_URL: http://lunary.188.245.152.205.sslip.io:3333