version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      APP_URL: ${APP_URL}
      API_URL: ${API_URL}
      # Add other backend env vars
    depends_on:
      - db

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "8080:8080"
    environment:
      API_URL: ${API_URL}
      NEXT_PUBLIC_API_URL: ${API_URL}
      # Add other frontend env vars
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lunary}
      POSTGRES_USER: ${POSTGRES_USER:-lunary}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
